### ISSUE TITLE
Decorations are applied on every doc change

### ISSUE THREAD

**Issue by christos8333** [b-kelly/prosemirror-highlightjs#3]
Hi, 
really nice plugin! 
I did try it out and seems like decorations are applied on every doc change, even if the change is not affecting a code_block node, resulting in a really 'slow' typing experience. This happens even if you just have 2-3 code blocks on the doc, or am I missing something? As I can get the plugin(just noticed it) I guess I can change that, but wondering if that what i should do.

**Comment by b-kelly** [comment]
Hey, thanks for using it!

Now that I take a second look, I believe you are right. On `apply` it does one of two things:
* no changes - map the decorations forward
* changes - run highlight.js and create decorations

I'll admit, I don't use the provided plugin "in production" since I have a much more specialized (but still very similar) plugin used there, so I haven't spent as much time getting the details on this one right.

That being said, I'm shipping it, so I should support it 🙂. I'll see if I can't get a fix out soon. When I do, I'll bump the npm version and report back here so you get a notification.

**Comment by b-kelly** [comment]
That was a bit more work than I expected, but I'm happy with the results. The issue is fixed, but I haven't bumped the package version yet. I'll do it tomorrow.

**Comment by christos8333** [comment]
That looks solid! thank you very much for your hard work. Yeah, i'll update when you publish, and delete my plugin, as I was doing a simple check if the node type in the selection is of nodeTypes to fire getHighlightDecorations to overcome the slow typing.

**Comment by b-kelly** [comment]
This is now live on npm. Let me know what you think!
